
classifier:
  _target_: trainer.ClassifierTrainer

  fp16: True
  grad_norm_clip_max: 0
  max_epoch: 10
  save_path: ${paths.save_folder}
  predict_save_path: ${result_dir}/predict/

  optimizer:
    target_type: torch.optim.AdamW
    kwargs:
      lr: 1e-4
      weight_decay: 1e-6
      fused: false

  lr_scheduler:
    target_type: transformers.get_cosine_schedule_with_warmup
    step:
      custom_enable: true
      per_mini_batch: true
      period: 1
      arg_name: num_training_steps
      total_count:
        scale: 1.3
        bias: 0
    kwargs:
      # num_training_steps: ${eval:45 * ${trainer.classifier.max_epoch} * 1.6}
      num_warmup_steps: 0
  
  criterion:
    bce:
      _target_: torch.nn.BCEWithLogitsLoss
  
  ema:
    enable: true
    decay: 0.9999
    update_start_step: 0


vessel_segment:
  _target_: trainer.VesselSegmentTrainer

  fold_index: 0
  fp16: True
  grad_norm_clip_max: 35
  max_epoch: 8
  save_path: ${paths.save_folder}

  optimizer:
    target_type: torch.optim.Adam
    kwargs:
      lr: 0.001

  lr_scheduler:
    target_type: torch.optim.lr_scheduler.LambdaLR
    kwargs:
      lr_lambda:
        _target_: utils.optim.LearningRater
        
        start: 0.002
        max: 0.01 #* strategy.num_replicas_in_sync
        min: 0.004
        rampup_epochs: 5
        sustain_epochs: 0
        exp_decay: 0.8
  
  criterion:
    bce:
      _target_: torch.nn.BCEWithLogitsLoss
  
  ema:
    enable: true
    decay: 0.9999
    update_start_step: 0


vessel_roi_bbox:
  _target_: trainer.VesselROIBBoxTrainer

  fold_index: 0
  fp16: True
  grad_norm_clip_max: 35
  max_epoch: 30
  save_path: ${paths.save_folder}

  optimizer:
    target_type: torch.optim.AdamW
    kwargs:
      lr: 3e-4
      weight_decay: 1e-6
      fused: True

  lr_scheduler:
    target_type: transformers.get_cosine_schedule_with_warmup
    step:
      custom_enable: true
      per_mini_batch: true
      period: 1
      arg_name: num_training_steps
      total_count:
        scale: 1.6
        bias: 0
    kwargs:
      # num_training_steps: ${len(train_loader)} * ${trainer.vessel_roi_bbox.max_epoch} * 1.6
      # num_training_steps: ${eval:45 * ${trainer.vessel_roi_bbox.max_epoch} * 1.6}
      # num_training_steps: 1440
      num_warmup_steps: 0
  
  criterion:
    mae:
      _target_: torch.nn.L1Loss
  
  ema:
    enable: true
    decay: 0.9999
    update_start_step: 0
