# @package _global_

defaults:
  - _self_
  - data: default
  - paths: default
  - hydra: default

experiment_name: preprocess_dcm_to_npy

train_target: ""

label_file_path: ${paths.data_root_dir}${data.common.label_file_name}
series_data_path: ${paths.data_root_dir}${data.common.series_data_folder_name}
# output_path: ${paths.data_root_dir}raw_data
output_path: H:/ml_data_resource/kaggle/intracranial_aneurysm_detection/raw_slide_data/

slide_metainfo_gen:
    enable: true
    output_path: H:/ml_data_resource/kaggle/intracranial_aneurysm_detection/raw_slide_data.csv

preprocess:
  _target_: dataset.preprocess.DICOMToNPYPreprocessor

  crop:
    enable: true
    info_file_path: ${paths.data_root_dir}series_crop_bbox_loss_20260129_153709.npy
  resize:
    enable: false
    target_shape: [352, 352]
    mode: bilinear

result_dir: ${paths.result_dir}/${experiment_name}
