# @package _global_

defaults:
  - _self_
  - data: default
  - paths: default
  - hydra: default

experiment_name: preprocess_vessel_seg_to_roi_bbox

train_target: ""

preprocess:
  _target_: dataset.preprocess.VesselSegToROIBBoxPreprocessor

  data_root_path: ${paths.data_root_dir}
  segment_folder_name: segmentations
  seg_output_name: segmentations_window1
  total_output_name: train_windows1_test1_
  series_slide_fileset_path: ${paths.data_root_dir}raw_slide_data/
  series_slide_metainfo_file_name: 'train_sampled_new.csv'
  num_series_slide: 48

result_dir: ${paths.result_dir}/${experiment_name}
