
classifier:
  _target_: models.DiseaseDetector

  input_volume_channels: ${data.common.input_channels}
  in_channels: 3
  num_classes: ${data.common.num_classes}

  backbone:
    _target_: timm.create_model
    
    model_name: resnet18
    pretrained: False
    in_chans: ${model.classifier.in_channels}
    global_pool: ''
    num_classes: 0


vessel_segment:
  _target_: models.VesselSegmentExtractor

  backbone:
    target_type: dynamic_network_architectures.architectures.unet.ResidualEncoderUNet
    kwargs:
      input_channels: 1
      n_stages: 6
      features_per_stage: [32, 64, 128, 256, 320, 320]
      conv_op:
        target_type: torch.nn.modules.conv.Conv3d
      # kernel_sizes: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
      kernel_sizes: [3, 3, 3, 3, 3, 3]
      # strides: [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]]
      strides: [1, 2, 2, 2, 2, 2]
      n_blocks_per_stage: [1, 3, 4, 6, 6, 6]
      num_classes: ${data.vessel_segment.num_mask_classes}
      n_conv_per_stage_decoder: [1, 1, 1, 1, 1]
      conv_bias: True
      norm_op:
        target_type: torch.nn.modules.instancenorm.InstanceNorm3d
      norm_op_kwargs:
        eps: 1e-05
        affine: True
      dropout_op: null
      dropout_op_kwargs: null
      nonlin:
        target_type: torch.nn.modules.activation.LeakyReLU
      nonlin_kwargs:
        inplace: True
      deep_supervision: True


vessel_roi_bbox:
  _target_: models.VesselROIBBoxExtractor

  depth_size: 48

  backbone:
    target_type: timm.create_model
    kwargs:
      model_name: vit_small_plus_patch16_dinov3.lvd1689m
      pretrained: False
      in_chans: 3
      global_pool: ''
      num_classes: 0
